const state={headers:[],rows:[],filtered:[],page:1,pageSize:15};
const $=id=>document.getElementById(id), norm=s=>String(s??'').trim().toLowerCase();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function findHeader(q){return state.headers.find(h=>norm(h).includes(norm(q)))||''}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2600)}
function save(){localStorage.setItem('siswa_kiupunu_v2',JSON.stringify({headers:state.headers,rows:state.rows,updatedAt:new Date().toISOString()}))}
function load(){try{const x=JSON.parse(localStorage.getItem('siswa_kiupunu_v2')||localStorage.getItem('siswa_kiupunu_v1'));if(x){state.headers=x.headers||[];state.rows=x.rows||[];$('lastUpdate').textContent=x.updatedAt?`Diperbarui ${new Date(x.updatedAt).toLocaleDateString('id-ID')}`:'Data tersimpan lokal'}}catch(e){}renderAll()}
function getGroups(){const rb=findHeader('Rombel Saat Ini'),g={};state.rows.forEach(r=>{const k=String(r[rb]||'Tidak diisi').trim()||'Tidak diisi';g[k]=(g[k]||0)+1});return Object.entries(g).sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true}))}
function renderAll(){dashboard();filters();table()}
function dashboard(){const jk=findHeader('JK');const a=getGroups(),total=state.rows.length,m=state.rows.filter(r=>norm(r[jk])==='l').length,f=state.rows.filter(r=>norm(r[jk])==='p').length;$('total').textContent=total;$('male').textContent=m;$('female').textContent=f;$('rombelCount').textContent=a.length;$('malePct').textContent=total?`${Math.round(m/total*100)}% dari total`:'0% dari total';$('femalePct').textContent=total?`${Math.round(f/total*100)}% dari total`:'0% dari total';
const chart=$('classChart');if(!a.length){chart.className='chart empty';chart.textContent='Belum ada data. Silakan import Excel.'}else{chart.className='chart';const max=Math.max(...a.map(x=>x[1]));chart.innerHTML=a.map(([n,c])=>`<div class="baritem"><div class="bar" style="height:${35+120*c/max}px"></div><b>${c}</b><span title="${esc(n)}">${esc(n)}</span></div>`).join('')}
const cc=$('classCards');if(!a.length)cc.innerHTML='<div class="empty-card">Belum ada data rombel.</div>';else{const max=Math.max(...a.map(x=>x[1]));cc.innerHTML=a.map(([n,c])=>`<div class="class-card"><b>${esc(n)}</b><span>${c} siswa</span><div class="mini-bar"><i style="width:${Math.round(c/max*100)}%"></i></div></div>`).join('')}}
function filters(){const rb=findHeader('Rombel Saat Ini'),cur=$('classFilter').value;const vals=[...new Set(state.rows.map(r=>String(r[rb]||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));$('classFilter').innerHTML='<option value="">Semua Rombel</option>'+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(vals.includes(cur))$('classFilter').value=cur}
function table(){const q=norm($('search').value),rb=findHeader('Rombel Saat Ini'),name=findHeader('Nama'),nipd=findHeader('NIPD'),nisn=findHeader('NISN'),jk=findHeader('JK'),nik=findHeader('NIK');state.filtered=state.rows.filter(r=>(!q||[r[name],r[nipd],r[nisn],r[nik]].some(v=>norm(v).includes(q)))&&(!$('classFilter').value||String(r[rb]||'')===$('classFilter').value));const pages=Math.max(1,Math.ceil(state.filtered.length/state.pageSize));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.pageSize,page=state.filtered.slice(start,start+state.pageSize);$('tbody').innerHTML=page.map((r,i)=>`<tr><td>${start+i+1}</td><td class="name">${esc(r[name])}</td><td>${esc(r[nipd])}</td><td>${esc(r[nisn])}</td><td>${esc(r[jk])}</td><td>${esc(r[rb])}</td><td><button class="linkbtn" data-index="${start+i}">Detail</button></td></tr>`).join('')||'<tr><td colspan="7" style="text-align:center;padding:35px;color:#98a2b3">Tidak ada data.</td></tr>';$('countInfo').textContent=`${state.filtered.length} data • halaman ${state.page}/${pages}`;$('prev').disabled=state.page<=1;$('next').disabled=state.page>=pages;document.querySelectorAll('.linkbtn').forEach(b=>b.onclick=()=>showDetail(state.filtered[Number(b.dataset.index)]))}
function showDetail(r){if(!r)return;const name=findHeader('Nama');const fields=state.headers.map(h=>`<div class="field"><label>${esc(h)}</label><b>${esc(r[h])||'—'}</b></div>`).join('');$('detail').innerHTML=`<div class="detail-head"><h2>${esc(r[name]||'Data Siswa')}</h2><p>Detail lengkap peserta didik</p></div><div class="detail-grid">${fields}</div>`;$('modal').classList.remove('hidden')}
function showView(id){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===id));const t={dashboard:['Dashboard','Ringkasan data peserta didik SD Negeri Kiupunu.'],data:['Data Peserta Didik','Cari, filter, dan lihat detail siswa.'],import:['Import Data Excel','Masukkan data dari file Excel sekolah.'],about:['Tentang Aplikasi','Informasi fitur dan kesiapan sistem.']}[id];$('pageTitle').textContent=t[0];$('pageSub').textContent=t[1]};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('importTop').onclick=()=>$('import').classList.contains('hidden')?showView('import'):null;$('quickData').onclick=()=>showView('data');$('quickImport').onclick=()=>showView('import');$('viewDataBtn').onclick=()=>showView('data');$('quickExport').onclick=()=>exportExcel();$('importTop').onclick=()=>showView('import');$('chooseBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>{if(e.target.files[0])readExcel(e.target.files[0]);e.target.value=''};
function readExcel(file){const fr=new FileReader();fr.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:'array',cellDates:true});const ws=wb.Sheets['Daftar Peserta Didik']||wb.Sheets[wb.SheetNames[0]];const aoa=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});if(aoa.length<7)throw Error('Format file tidak sesuai.');const top=aoa[4]||[],sub=aoa[5]||[];state.headers=top.map((v,i)=>{const a=String(v||'').trim(),b=String(sub[i]||'').trim();return a&&b?`${a} - ${b}`:(a||b||`Kolom ${i+1}`)});state.rows=aoa.slice(6).filter(r=>String(r[0]??'').trim()!=='').map(r=>Object.fromEntries(state.headers.map((h,i)=>[h,r[i]??''])));state.page=1;save();$('lastUpdate').textContent=`Diperbarui ${new Date().toLocaleDateString('id-ID')}`;renderAll();renderPreview();toast(`Berhasil mengimpor ${state.rows.length} data siswa.`);showView('data')}catch(err){toast('Gagal membaca Excel: '+err.message)}};fr.readAsArrayBuffer(file)}
function renderPreview(){$('preview').innerHTML=`<div class="preview"><h3>Hasil Import</h3><p><b>${state.rows.length}</b> siswa terbaca. Contoh 10 data pertama:</p><div class="preview-table"><table><thead><tr><th>No</th><th>Nama</th><th>NISN</th><th>JK</th><th>Rombel</th></tr></thead><tbody>${state.rows.slice(0,10).map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r[findHeader('Nama')])}</td><td>${esc(r[findHeader('NISN')])}</td><td>${esc(r[findHeader('JK')])}</td><td>${esc(r[findHeader('Rombel Saat Ini')])}</td></tr>`).join('')}</tbody></table></div></div>`}
function exportExcel(){if(!state.rows.length)return toast('Belum ada data untuk diekspor.');const aoa=[state.headers,...state.rows.map(r=>state.headers.map(h=>r[h]??''))];const ws=XLSX.utils.aoa_to_sheet(aoa),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Data Siswa');XLSX.writeFile(wb,'Data_Siswa_SD_Negeri_Kiupunu.xlsx')}
$('search').oninput=()=>{state.page=1;table()};$('classFilter').onchange=()=>{state.page=1;table()};$('exportBtn').onclick=exportExcel;$('prev').onclick=()=>{if(state.page>1){state.page--;table()}};$('next').onclick=()=>{state.page++;table()};$('closeModal').onclick=()=>$('modal').classList.add('hidden');$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.add('hidden')};const dz=$('dropzone');['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.style.borderColor='#315efb'}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.style.borderColor='#cfd7e6'}));dz.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f)readExcel(f)});load();
